
# Hardware

This chapter provides an overview of Vibe's hardware components.

**The following is covered in this chapter:**

-  [2.1 Console](#Console-2.1)
-  [2.2 Wings](#Wings-2.2)
-  [2.3 Connectors](#Connectors-2.3)
-  [2.4 Editor HardKeys](#Editor-HardKeys-2.4)
-  [2.5 Master Controls](#Master-Controls-2.5)
-  [2.6 Playback Controls](#Playback-Controls-2.6)
-  [2.7 Controller Keys](#Controller-Keys-2.7)
-  [2.8 Page Keys](#Page-Keys-2.8)


## Console {#Console-2.1}


The Vibe Family has the following console models:

 • **\[Vibe]**: the main model designed for wide entertainment productions.
 
 • **\[Vibe M]**: the middle range model designed for theater and television studios.
 
 • **\[Vibey]**: the compact model designed for live concerts and touring productions.
 

The consoles share the same programming features but they have a different hardware composition, mostly related to: the overall dimension, the number of integrated monitors, the In/Out on-board connectors, and the quantity of physical controllers.


<p align=center>**VIBE**</p>
`r create_image_tag("02.Hardware", "2.1-Vibe-front")`

Built-in 21.5” plus 11.6” Full HD multi-touch screens

Length: 977mm (38.4in)

Width: 436mm (17.1in)

Height (closed): 155mm (6.1in)

Height (opened): 458mm (18in)

Weight: 26.7kg (60.0lb)

15 individually paging motorized faders

35 individually paging multi-use controller buttons

5 general purpose faders


<p align=center>**VIBE M**</p>
`r create_image_tag("02.Hardware", "2.1-VibeM-front")`

Built-in 15.6” plus 11.6” Full HD multi-touch screens

Length: 882mm (34.7in)

Width: 436mm (17.1in)

Height (closed): 155mm (6.1in)

Height (opened): 396mm (15.5in)

Weight: 22.8kg (50.2lb)

10 individually paging motorized faders

30 individually paging multi-use controller buttons


<p align=center>**VIBEY**</p>
`r create_image_tag("02.Hardware", "2.1-Vibey-front")`


Built-in 21.5” Full HD multi-touch screen

Width: 720mm (28.3in)

Depth: 445mm (17.5in)

Height (closed): 166mm (6.5in)

Height (opened): 470mm (18.5in)

Weight: 19.5kg (43.0lb)

10 individually paging motorized faders

10 individually paging multi-use encoders

20 individually paging multi-use controller buttons


All the consoles run the same Vibe software, that is also available in a free demo PC version for Windows operative systems. 


<p align=center>**VIBE PC**</p>
`r create_image_tag("02.Hardware", "2.1-VibePC")`

Vibe PC is a useful tool for console training, feature and fixture test, remote programming and live lighting control as well. It may be used to communicate with a 3D visualizer and to pre-program show files, that can be easily moved between any Vibe system.

The free unlicensed Vibe PC software has the following limitations:
- outputs of up to 64 universes on VC protocol,
- outputs of up to 1 universe on ArtNet and 1 universe on sACN protocols,
- random blackout of 10 seconds every 5/20 minutes on ArtNet and sACN protocols,
- networking connection to other Vibe systems is not available.


## Wings {#Wings-2.2}


The Vibe Family has the following wing models:
 • **\[Vibe PC Wing]**: the Vibe panel, designed for touring events and freelance operators.

Vibe PC Wing features the editor panel and the playback panel with the same size and capabilities of the compact Vibey console.

Vibe PC Wing can be used in network with any Vibe Console running as a control expansion, or connected to the Vibe PC software providing the physical editor panel and controllers.

 
<p align=center>**VIBE PC WING**</p>
`r create_image_tag("02.Hardware", "2.2-Vibe-PC-Wing-front")`

Width: 654mm (25.75")

Depth: 339.1mm (13.35")

Height: Height: 95.7mm (3.7")

Weight: 6.5Kg (14.33lb)

10 individually paging motorized faders

10 individually paging multi-use encoders

20 individually paging multi-use controller buttons
 
 
## Connectors {#Connectors-2.3}


The Vibe Consoles and Wings have the following In/Out connectors:


<p align=center>**Vibe**</p>
`r create_image_tag("02.Hardware", "2.3-Vibe-rear")`

8 Physical DMX 512 input/output ports (RDM supported).

64 standard DMX over Ethernet universes, up to 256 DMX universes via license.

Support for Compulite VC, Art-Net 3, and sACN protocols. 

MIDI In/Out 5-pin DIN.

SMPTE In Combo XLR.

2 EtherCON ports for the Data network.

2 RJ45 Ethernet ports for accessories and additional devices, such as NAS storage.

4 USB3 ports on the back panel.

2 USB2 ports on the front panel.

3.5mm Audio line in/out.

3.5mm Mic in.

3.5mm Speaker out.

2 DisplayPort video outputs.

XLR Desklight port.

PowerCon AC Input


<p align=center>**Vibe M**</p>
`r create_image_tag("02.Hardware", "2.3-VibeM-rear")`

8 Physical DMX 512 input/output ports (RDM supported).

64 standard DMX over Ethernet universes, up to 256 DMX universes via license.

Support for Compulite VC, Art-Net 3, and sACN protocols. 

MIDI In/Out 5-pin DIN.

SMPTE In Combo XLR.

2 EtherCON ports for the Data network.

2 RJ45 Ethernet ports for accessories and additional devices, such as NAS storage.

4 USB3 ports on the back panel.

2 USB2 ports on the front panel.

3.5mm audio line in/out.

3.5mm Mic in.

3.5mm Speaker out.

2 DisplayPort video outputs.

XLR Desklight port.

PowerCon AC Input


<p align=center>**Vibey**</p>
`r create_image_tag("02.Hardware", "2.3-Vibey-rear")`

4 Physical DMX 512 input/output ports (RDM supported).

64 standard DMX over Ethernet universes, up to 256 DMX universes via license.

Support for Compulite VC, Art-Net 3, and sACN protocols. 

MIDI In/Out 5-pin DIN.

SMPTE In Combo XLR.

1 EtherCON port for the Data network.

2 RJ45 Ethernet ports for accessories and additional devices, such as NAS storage.

4 USB3 ports on the back panel.

3 USB2 ports on the front panel.

3.5mm audio line in/out.

3.5mm Mic in.

3.5mm Speaker out.

2 DisplayPort video output.

1 XLR Desklight port.

PowerCon AC Input


<p align=center>**Vibe PC Wing**</p>
`r create_image_tag("02.Hardware", "2.3-Vibe-PC-Wing-rear")`

4 Physical DMX 512 input/output ports (RDM supported).

64 standard DMX over Ethernet universes on VC protocol. 

16 standard DMX over Ethernet universes on Art-Net 3 and sACN protocols. 

MIDI In/Out 5-pin DIN.

SMPTE In Combo XLR.

2 EtherCON ports for the Data network, accessories and additional devices.

3.5mm audio line in/out.

3.5mm Mic in.

3.5mm Speaker out.

PowerCon AC Input


## Editor HardKeys {#Editor-HardKeys-2.4}


Editor Controls are used to program and edit parameter values for all fixtures as well as to create and edit objects such as cues and libraries.
 
<p align=center>**Editor**</p>
`r create_image_tag("02.Hardware", "2.4-Editor", "500")`

 • 1 Dedicated dimmer wheel
 
 • 4 Main encoder push wheels
 
 • 4 Extra encoder push wheels
 
 • 1 Trackball
 
 • **\[Next] / \[Prev]** Keys
 
 • XYZ lock keys
 
 • **\[Res]** Wheel resolution key
 
 • Numeric Key Pad 
 
 • **\[Vibe]** Key (Shift button)
 
 • Editor Command keys
 
 • Object Select keys


## Master Controls {#Master-Controls-2.5}


Master Controls are used to trigger the Controller assigned as the Master and to limit the intensity of all the fixtures.
 
<p align=center>**Grand Master and BlackOut**</p>
`r create_image_tag("02.Hardware", "2.5-GM+BO", "500")`

 • **\[Grand Master]** Slider.
 
 • **\[BO]** Blackout key.

<p align=center>**A/B and Master Keys**</p>
`r create_image_tag("02.Hardware", "2.5-Master+AB", "500")`

 • **\[GO/BACK/HOLD]** keys for executing cues on the Master Controller.
 
 • **A/B CrossFader** non-motorized pair of sliders for executing Qlists and Cues manually.


## Playback Controls {#Playback-Controls-2.6}


Playback Controls are used to trigger the Objects assigned to the controller.

<p align=center>**Playback**</p>
`r create_image_tag("02.Hardware", "2.6-Playback", "500")`

 • Individually paging **Slider Set Controllers** with motorized fader and three buttons for for the execution and control of Qlists, Cues, Scenes, Group Masters (Submasters), Rate Masters, Flash Masters.
 
 • Individually paging **Qkey Controllers** with pressable knob or single button for the execution of Qlists, Cues, Scenes, Groups selection, Libraries, Snaps, Macros, Rate.

 • Individually paging **Auxiliary Key Controllers** with single button for the execution of Qlists, Cues, Scenes, Groups selection, Libraries, Snaps, Macros.
 
 • Non-paging **Global Slider Controllers** with non-motorized fader and single button for the execution and control of Qlists, Cues, Scenes, Group Masters (Submasters), Rate Masters, Flash Masters.


## Controller Keys {#Controller-Keys-2.7}


Controller Keys are used to select and trigger the controllers.
These keys are divided into two groups: Operation Keys and Command Keys.

**\[Operation Keys]** manage the assignments to the controllers.
 
<p align=center>**Operation Keys**</p>
`r create_image_tag("02.Hardware", "2.7-Operation-Keys")`

 • **\[SELECT]** key to assign the Master Controller.
 
 • **\[LOAD]** key to pre-load a controller for execution.
 
 • **\[RELEASE]** Key to release a target controller.
 
 • **\[FREE]** Key to empty a target controller.
 
 • **\[SNAP GO]** Key to trigger a Snap.
 
 • **\[PROTECT]** Key to lock the desk with a password.
 
**\[Command Keys]** provide additional functions to the controllers.
 
<p align=center>**Command Keys**</p>
`r create_image_tag("02.Hardware", "2.7-Command-Keys", "500")`

 • **\[FLASH]** makes the target controller flash.
 
 • **\[SOLO]** releases the other controllers, allowing only one controller to be triggered at once.
 
 • **\[GO RELEASE]** makes a Go and Release command to the target controller.
 
 • **\[ON]** activates the target controller.
 
 • **\[OFF]** deactivates the target controller.
 
 • **\[LATCH]** (not implemented yet).
 
 • **\[GO]** makes a Go command to the target controller.
 
 • **\[HOLD BACK]** makes a Hold and Back command to the target controller.
 
 • **\[<--->]** reverses the order of the Cues on the target controller.
 
 • **\[>>>]** makes a Step forward to the target controller (Go in Cut time).
 
 • **\[<<<]** makes a Step backward to the target controller (Back in Cut time).
 
 • **\[ASSERT]** makes a Go command to the current Cue on the target controller.
 
 • **\[RATE]** for overall or individual rate override of the controllers.
 
 • **\[TEACH]** for assigning the BPM tap time of the controllers.


## Page Keys {#Page-Keys-2.8}


Page Keys are used to quickly move between the pages.

<p align=center>**Page Keys**</p>
`r create_image_tag("02.Hardware", "2.8-Page-Keys", "200")`

  • **\[VIEW]** Accesses the Pages View.

  • **\[PATCH]** switches between Patch Pages.

  • **\[PROGRAM]** switches between Program Pages.

  • **\[PLAYBACK]** switches between Playback Pages.


Vibe Pages can be also switched from the screen's Toolbar by tapping the Home Page buttons, or through the keyboard by pressing F1, F2, F3, F4 function buttons.

