
# Patch

👉 **Patch** the Vibe in a few short passages: import devices, create fixtures, assign addresses and output the DMX signal.

This chapter deals with creating and patching fixtures.

**Chapter index:**

-  [5.1 Sets](#Sets-5.1)
-  [5.2 Devices](#Devices-5.2)
-  [5.3 Create and Patch](#Create-and-Patch-5.3)
-  [5.4 DMX Properties](#DMX-Properties-5.4)
-  [5.5 Fixture View](#Fixture-View-5.5)
-  [5.6 Address Properties](#Address-Properties-5.6)
-  [5.7 Park](#Park-5.7)
-  [5.8 Clone](#Clone-5.8)
-  [5.9 Replace](#Replace-5.9)
-  [5.10 Calibration](#Calibration-5.10)
-  [5.11 Auto-Patch](#Auto-Patch-5.11)


## Sets {#Sets-5.1}


Vibe contains an extensive **Device Library** with DMX parameter mapping for fixtures, media servers, and common miscellaneous devices like smoke machines. 
Before a device can be programmed it must be imported and patched to DMX addresses. 

Vibe has an advanced numbering system that allows devices to be grouped into five familiar categories called **SETS**. 

The Default Sets are Fixture, Channel, Spot, Matrix, Media Server. Additional custom **SETS** may also be created. Fixture numbering in all sets can be freely changed if there are no overlapping numbers. Each Set has a unique ID.

**Set ID numbers:** 

  - 0 = **\[Fixture]** is a special global numbering set that must also reference one of the other sets. All devices must be assigned a Fixture number and one of the other set numbers. 

  - 1 = **\[Channel]** is a numbering set that would normally be used for conventional single parameter devices. 

  - 2 = **\[SPOT]** is a numbering set that would mainly be used for multi-parameter devices like moving lights. 

  - 3 = **\[MATRIX]** is a numbering set that would mainly be used for RGB or other non-moving LED fixtures, also useful for pixel mapping devices.

  - 4 = **\[SERVER]** is a numbering system used for media servers.

Each **SET** may have Fixtures numbered from 1 ⟶ 999999 

To patch a device, you must first move focus to the main monitor and press the \[PATCH] Workspace Template key. By default, the first page will contain all the displays needed for patching.

### Add Sets

The option to add a user-created set is done via the Sets view.

**To Add a Set**

1. Add a Sets view: 

- Open _Vibe_ menu

- Tap Patch

- Tap Sets

2. On the Sets view tap the Add icon on the header

3. On the popup define the set's name and number

4. Tap apply

`r create_image_tag("05.Patch", "5.1-Sets")`

### Edit Sets

There is an option to edit a user-created set. This is done via the Sets view.

**To Edit a Set**

1. Add a Sets view: 

- Open _Vibe_ menu

- Tap Patch

- Tap Sets

2. On the Sets view select a user-created set

3. Tap the Edit icon on the header


## Devices {#Devices-5.2}


**Once the Patch Page is open:**

1. Use the Devices view.
    
2. Tap {Import}, the Manufactures picker list will appear.
    
`r create_image_tag("05.Patch", "5.2-Devices-Import")`
    
3. Flick or drag along the list to browse to the desired manufacturer then tap the manufacturer's name.
    
4.  A new list and search window will open. If the exact device name is known, type it in the search window, if not flick or drag to browse the list until the desired device is found.
    
`r create_image_tag("05.Patch", "5.2-Devices")`
    
5. The < key may be pressed at any time to return to the imported Devices list.
    
`r create_image_tag("05.Patch", "5.2-Search-Bar")`

### Advanced Search

Fixtures may be searched directly by name using the **Advanced Device Search**. 

Searches may be filtered by parameter order and DMX Channel Count to limit the search. 

👉 The filters are very helpful in finding close matches for fixtures that are not currently in the device library.

**To access Advanced Search:**

1. Tap {Import} on the Devices view header - The tab will show {Advanced Search}.
    
2. Tap {Advanced Search} - The Advanced Search Pop-up will appear.
    
3. Type the fixture's name in the Fixture Name box, set the number of channels, or select the parameters to filters the devices database.
    
4. Select the fixture from the Matching Devices list.

`r create_image_tag("05.Patch", "5.2-Advanced-Device-Search")`

5. The DMX Modes pop-up will open. 

6. Review the DMX chart and select the desired mode. 

7. Tap Apply or Import or press \[ENTER] to close the popup and add the fixture to the Imported Devices list.

`r create_image_tag("05.Patch", "5.2-Device-Import-sample")`


## Create and Patch {#Create-and-Patch-5.3}


**To open the Create and Patch popup:**

1. Import the desired device.
    
2. The device will now be in the list below the Imported Devices header.
    
3. Tap the device you wish to patch and the Create and Patch Fixtures popup will appear.
    
`r create_image_tag("05.Patch", "5.3-Create-and-Patch")`

**To Create and Patch fixtures:**

1. In the **Create and Patch** pop-up, type the quantity in the red highlighted field via the keypad or flick/drag to browse the list until the desired quantity number is found then tap the number.
    
2. If the **Quantity** number is not highlighted in <span style="color:Red">Red</span>, tap the field to make it active.
    
3. Press the ⟶ key on the keypad to tab to the next field, or tap in the {SET} field. The appropriate SET for the selected fixture should automatically be selected, but as some fixtures don't always cleanly fit into standard categories, check that the correct Set is selected. If not, flick/drag to browse to the correct SET then tap it. You may also type the Set number (0-5).
    
4. Press the ⟶ key on the keypad to tab to the {Set Number} field.
    
5. Set the Channel, Spot, Matrix, or Server number for the fixture in the red highlighted field using the keypad or scroll to browse the list until the desired start number is found, then tap the number. 
👉 By default, the first available number for the selected SET is pre-assigned.
    
6. Press the ⟶ key on the keypad to tab to the next field, or tap any box in the Fixture Number field to select it.
    
7. By default, the same number as the SET Number will appear as the Fixture Number. Many users like to group Fixtures by 10ʼs or 100ʼs so it is common to type 101 for the start of one type of fixture, 201 for a second type and so on. The SET number and Fixture number do not have to be the same.
    
8. Next to the Fixture Number field is a data entry box that displays the fixture's default short name. This may be edited at any time while in this pop-up. The name will be updated when the fixtures are created upon closing the popup.
    
9. In the second section of the pop-up, fixtures that were selected for creation can be patched via the DMX patch wizard. Press the ⟶ key on the keypad to tab to the next field, or tap a number in the UNIVERSE field. If the desired universe is not visible, flick/drag to browse to the correct universe number then tap it.
    
10. Press the ⟶ key on the keypad to tab to the next field, or tap any number in the **ADDRESS** field.

👉 By default, the interval between fixtures of the same type is fixed.
Using the **INTERVAL** field, a custom interval may be set.

11. To complete **CREATE and PATCH** tap the **{APPLY & CONTINUE}** key in the bottom **right corner of the popup**, Press **\[ENTER]**, or tap Apply to close the popup and return to the patch workspace.

**Theatrical Multi-Patching can also be done manually using keypad syntax:**

  - Toggle off the **{MAIN PATCH}** key at the top of the DMX patch wizard before closing the pop-up. The fixtures will be created but will remain unpatched.

**To Patch fixtures using traditional keypad syntax:**

  - \[FIXTURE] \[#] \[ADDRESS] \[#].\[#] 
  
👉 By default, the first available DMX address of the selected Universe will be shown in the **ADDRESS** field. If the default start address is not appropriate, type or scroll the list to the desired start address and tap it.Universe.Address, \[STORE]. **Or** 

  - \[ADDRESS] \[#].\[#] +/ - ⟶ \[#].\[#] \[FIXTURE] \[#] \[STORE].

👉 Addresses may also be typed in absolute format: 1 ⟶ 32,768 (64 Universes standard). The system will automatically assign the correct universe.
 
👉 When starting from a {New Show} only {Physical DMX outputs} are enabled. Network universes must be enabled in **PATCH** {DMX Settings}

### Drag and Drop Patch

If {Main Patch} is toggled off in the Create and Patch pop-up, fixtures can be created but not patched. Created fixtures may then be dragged and dropped onto the Universe View.

`r create_image_tag("05.Patch", "5.3-Universe-View")`

**Drag and Drop from the Fixtures tab:**

1. Create fixtures.
    
2. Select the Fixture **Set** you wish to patch from the Set list.

`r create_image_tag("05.Patch", "5.3-Sets-View")`
    
3. Select a destination **Universe** from the Universes list. The universe grid will be shown in the Universes view.

`r create_image_tag("05.Patch", "5.3-Universes")`

4. Select the **Fixtures** you wish to patch from the Fixtures list.
👉 Multiple fixtures may be selected by swiping ⤴ or ⤵ in the Fixtures list.

`r create_image_tag("05.Patch", "5.3-Fixtures")`

5. **Press and Hold** the fixtures, they will turn into floating icons.
    
6. Drag the fixture icons from the Fixtures view onto the Universe View grid. All associated DMX addresses will turn green. Drop the fixture icon on the desired DMX start address

7. The fixtures are now patched.
    
**Make multiple selections of fixtures using the keypad:**

1. Type a range of fixtures using the keypad - the fixture selection will be displayed numerically in the **Selection** box.
    
2.  **Press and Hold** anywhere in the Selection box - a fixture icon will appear.
    
3. Drag the icon to the Universe View grid and drop it at the destination start address.

4. The range of fixtures is now patched.
    
**Multi-Patch using Drag and Drop:**

1. Drag and drop the same fixture to multiple DMX offsets.
    
👉 All types of fixtures may be multi-patched but caution should be used when multi-patching multi-parameter fixtures.

**Unpatch fixtures using drag and drop:**

1. **Press and Hold** any patched DMX offset - The DMX addresses for the fixtures patched to it will turn green and a fixture icon will be shown.
    
2. Drag the selected block of fixtures towards the bottom of the screen - a waste bin icon will appear.
    
3. Drag the block until the icon is over the waste bin and drop the fixtures.

4. The fixtures are now unpatched.  

### Modify Patch

Once patched fixtures can be modified using keypad syntax or using the **Patch Toolbar**.

`r create_image_tag("05.Patch", "5.3-Patch-Toolbar")`

  - {CLEAR PATCH} - Opens the Clear Patch popup. 
    
  - {DELETE FIXTURE} - Opens the Delete Fixtures popup.

  - {CLONE} - Opens the Fixture Cloning popup.

  - {REPLACE} - Opens the Device Replacement popup.

  - {ADD FIXTURE} - Opens the Create And Patch popup. 
  
  - {PATCH} - Opens the Patch Fixture popup. 
  
  - {RENUMBER} - Opens the Renumber Fixture popup. 

  - {AUTO GENERATE} - Opens the Auto Generate popup. 
  
  - {FIXTURE CALIBRATION} - Opens the Fixture Calibration popup. 
  
**Modify the patch using keypad syntax:** 

  - \[FIXTURE] \[#] {CLEAR PATCH} - From the Editor toolbar. 

  - \[FIXTURE] \[#] \[DELETE] - Only works in the Patch Page.
    
### Address Test

Sometimes, especially in theatrical environments, it is useful to check if a DMX channel is empty or not. This can be done from the console by enabling the Address Test function on the header of the Universe View.

`r create_image_tag("05.Patch", "5.3-Address-Test")`

In Address Test mode each selected channel is visualized with a yellow background and it is forced to jump at full intensity.

Many channels can be selected by dragging or through multiple touches.

\[RESET] releases the channels and disables the Address Test function.

Once the function is disabled all the channels come back to their normal state.


## DMX Properties {#DMX-Properties-5.4}


The DMX Properties is divided in 4 sections corresponding to the 4 output types supported:

- Local Output: the physical DMX port embedded in the console.

- VC's: Compulite proprietary protocol for DMX over Ethernet.

- ArtNet: The most diffused protocol for DMX over Ethernet used for lighting fixture control.

- sACN: The most diffused protocol for DMX over Ethernet used for lighting fixture control and communication with other equipment related to show lighting (such as Tracking systems).

Most of the options and configuration properties are common to all the protocols, but a few of them are specific to the selected protocol and will be grayed out or not available.

Vibe is capable of transmitting more than one protocol at a time on the same Ethernet port. 

To save bandwidth it is also possible to enable only the universes for each protocol that are required. 

Vibe has separate universe patches for Local, VCs, Art-Net, and sACN. 

By default, on each protocol universes are patched on a 1:1 basis. 

It is possible to reroute universe output destinations. 

DMX can be remapped as needed to anyone of the supported 256 DMX universes.

The Vibe console is licensed to output from 64 up to 256 source universes, but these universes may be freely rerouted to any destination universe from 0 ⟶  256 as long as the total amount of universes does not exceed the purchased license.

**Available Universes**

In the bottom left of the popup, a red framed box informs about the amount of universes that the system can output on each protocol.

This number is based on the connected devices, summing each device universes to reach the system's total amount:

- Vibe PC software by default enables up to 64 input and output universes on VC's protocol and up to 1 universe on ArtNet and ACN protocols.

👉 If no PC Wing is connected to the Vibe PC, then the VibePC works in Demo Mode and the ArtNet and ACN protocols will get random 10 seconds blackouts, advised by a Red box on the toolbar. VC's protocol is not affected by the random blackouts.

- Vibe consoles by default enable up to 64 input and output universes.

👉 <span style="color:gray"> Vibe consoles support up to 256 universes output; to expand the 64 default universes the console needs to install a **Universe Licence**. Not implemented yet.</span>.

- Vibe consoles Local Universes depend on the quantity of embedded DMX ports.

- Vibe (and Vector) PC Wings add up to 16 input and output universes on ArtNet and ACN protocols.

- ePort8 Nodes add up to 8 input and output universes on ArtNet and ACN protocols.

- ePort41 Nodes add up to 5 input and output universes on ArtNet and ACN protocols.

- ePort2 Nodes add up to 2 input and output universes on ArtNet and ACN protocols.

### Local Output

`r create_image_tag("05.Patch", "5.4-DMX-Settings-Local")`

**Enable Local output**

- Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.

1. Under the Protocol heading, tap {Local Output} - The selection will turn red.
    
2. Under Broadcast Options tap {Out} - The status indicator light will turn green. The console will now be outputting the selected protocol on the EtherCON Data ports.
    
**Reroute Console Universes:**

1. Under the **Source Universe** header, scroll the list to the source console universe number you wish to route. Once tapped, the selection will turn red. A universe number may also be typed from the keypad.
    
2. Under the **Destination Universe** header, tap one of the cells in the destination universe grid. The source universe number will now be routed through the destination universe number.
    
**Additional functions:**

- Clear a destination universe - Tap {Universe #} in the destination grid. Tap {Clear}.
    
- Clear all destination universes - Select the protocol to clear. Tap {Clear All}.
    
- Reset default route for a single destination universe - Tap {Universe #} Tap {Config}.
    
- Reset all defaults for the selected protocol - Tap {Config All}.

**Enable Input / Output**

Use the Broadcast Option keys to enable / disable the Input and the Output, to either receive or send the protocol.

When the green dot is shown on the key, the protocol is set as enabled. Tap apply to activate it.

**Remap  Input / Output**

Toggle between In (Receive) and Out (Send) on the top of the view to either show the input or the output universes configuration in the destination universe box.

1. Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.
    
2. In the Protocol column, Tap {Local Output}.
    
3. Under the Source Universe heading, tap the desired source universe number or once red type the universe number you wish to be the source.
    
4. Under the Local Output Destination Universe heading, tap one of the displayed local outputs - the source Universe will now be patched to the output.

👉 Use the Clear All and the Config All keys to remap the protocol on a 1:1 basis.
  
**Change output to input** 

- Currently Vibe supports 2 inputs but multiple connectors may be assigned to the same input.

1. Tap a patched output - Two additional options will light up near the Output Destination Universe box. 

  - {Make Input 1} - Makes the selected outputs into Input 1. The Physical connector display will turn white to indicate it is now an input. 

  - {Make Input 2} - Makes the selected outputs into Input 2. The Physical connector display will turn white to indicate it is now an input.
    
**Change input to output**

1. Tap a patched input - an additional Make Output option will light up near the Output Destination Universe box.
    
2. Tap {Make Output} - The Connector will now output DMX.
    
**DMX refresh rate**

Sometimes older equipment cannot handle the higher refresh rates, so it may be reduced with the DMX Max Rate wheel. It is not recommended to go below 28Hz as some flickering may be observed.

👉 If VibePC is used to control an external software, such as a lighting visualizer, running on the same computer, the Local Outputs are used to communicate the VC's protocol to the other software using the loopback IP address 127.0.0.1.

### VC

`r create_image_tag("05.Patch", "5.4-DMX-Settings-VCs")`

**Enable VC output**

- Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.

1. Under the Protocol heading, tap {VC's} - The selection will turn red.
    
2. Under Broadcast Options tap {Out} - The status indicator light will turn green. The console will now be outputting the selected protocol on the EtherCON Data ports.
    
**Reroute Console Universes:**

1. Under the **Source Universe** header, scroll the list to the source console universe number you wish to route. Once tapped, the selection will turn red. A universe number may also be typed from the keypad.
    
2. Under the **Destination Universe** header, tap one of the cells in the destination universe grid. The source universe number will now be routed through the destination universe number.
    
**Additional functions:**

- Clear a destination universe - Tap {Universe #} in the destination grid. Tap {Clear}.
    
- Clear all destination universes - Select the protocol to clear. Tap {Clear All}.
    
- Reset default route for a single destination universe - Tap {Universe #} Tap {Config}.
    
- Reset all defaults for the selected protocol - Tap {Config All}.

**Enable Input / Output**

Use the Broadcast Option keys to enable / disable the Input and the Output, to either receive or send the protocol.

When the green dot is shown on the key, the protocol is set as enabled. Tap apply to activate it.

**Remap Input / Output**

Toggle between In (Receive) and Out (Send) on the top of the view to either show the input or the output universes configuration in the destination universe box.

1. Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.
    
2. In the Protocol column, Tap {VC's}.
    
3. Under the Source Universe heading, tap the desired source universe number or once red type the universe number you wish to be the source.
    
4. Under the Local Output Destination Universe heading, tap one of the displayed local outputs - the source Universe will now be patched to the output.

👉 Use the Clear All and the Config All keys to remap the protocol on a 1:1 basis.
    
**Change output to input** 

- Currently Vibe supports 2 inputs but multiple connectors may be assigned to the same input.

1. Tap a patched output - Two additional options will light up near the Output Destination Universe box. 

  - {Make Input 1} - Makes the selected outputs into Input 1. The Physical connector display will turn white to indicate it is now an input. 

  - {Make Input 2} - Makes the selected outputs into Input 2. The Physical connector display will turn white to indicate it is now an input.
    
**Change input to output**

1. Tap a patched input - an additional Make Output option will light up near the Output Destination Universe box.
    
2. Tap {Make Output} - The Connector will now output DMX.
    
**DMX refresh rate**

Sometimes older equipment cannot handle the higher refresh rates, so it may be reduced with the DMX Max Rate wheel. It is not recommended to go below 28Hz as some flickering may be observed.

**Unicast**

By default the protocol transmission is Broadcast, if a Unicast or Multicast transmission needs to be set, tap on the Unicast Settings toggle key. It is possible to set specific IPs to send the output to. If there is a port configured to a specific IP it will not be sent broadcast. 

The Unicast Settings allow to Add or Delete the IP addresses that will be used for the Unicast or Multicast transmission.

Any IP address may receive the whole protocol with all its universes, or only a part of it as defined in the "From Port" and "To Port" fields.

Ports that are not defined as unicast will be still sent as broadcast. 

Each port can be configured to multiple IPs, more ports can be sent to the same IP.

**Configure Unicast:**

1. Tap on the protocol in DMX Settings popup.

2. Toggle to _Unicast Settings_ to open the unicast popup.

3. Tap Add to add a new IP line or Delete to remove an existing IP

`r create_image_tag("05.Patch", "5.4-Unicast-Settings")`

> On the first line – ports 1 ⟶ 5 will be sent to IP 172.16.10.10

> On the second line – port 5 will be sent also to IP 172.16.10.11

> On the third line – ports 6 ⟶ 10 will be sent to IP 172.16.10.12

### ArtNet

`r create_image_tag("05.Patch", "5.4-DMX-Settings-ArtNet")`

**Enable ArtNet output**

- Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.

1. Under the Protocol heading, tap {ArtNet} - The selection will turn red.
    
2. Under Broadcast Options tap {Out} - The status indicator light will turn green. The console will now be outputting the selected protocol on the EtherCON Data ports.
    
**Reroute Console Universes:**

1. Under the **Source Universe** header, scroll the list to the source console universe number you wish to route. Once tapped, the selection will turn red. A universe number may also be typed from the keypad.
    
2. Under the **Destination Universe** header, tap one of the cells in the destination universe grid. The source universe number will now be routed through the destination universe number.
    
**Additional functions:**

- Clear a destination universe - Tap {Universe #} in the destination grid. Tap {Clear}.
    
- Clear all destination universes - Select the protocol to clear. Tap {Clear All}.
    
- Reset default route for a single destination universe - Tap {Universe #} Tap {Config}.
    
- Reset all defaults for the selected protocol - Tap {Config All}.

**Enable Input / Output**

Use the Broadcast Option keys to enable / disable the Input and the Output, to either receive or send the protocol.

When the green dot is shown on the key, the protocol is set as enabled. Tap apply to activate it.

<span style="color:blue">**Input** on the ArtNet protocol is not implemented yet.</span>.

**Remap Input / Output**

Toggle between In (Receive) and Out (Send) on the top of the view to either show the input or the output universes configuration in the destination universe box.

1. Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.
    
2. In the Protocol column, Tap {ArtNet}.
    
3. Under the Source Universe heading, tap the desired source universe number or once red type the universe number you wish to be the source.
    
4. Under the Local Output Destination Universe heading, tap one of the displayed local outputs - the source Universe will now be patched to the output.

👉 Use the Clear All and the Config All keys to remap the protocol on a 1:1 basis.

**Change output to input** 

- Currently Vibe supports 2 inputs but multiple connectors may be assigned to the same input.

1. Tap a patched output - Two additional options will light up near the Output Destination Universe box. 

  - {Make Input 1} - Makes the selected outputs into Input 1. The Physical connector display will turn white to indicate it is now an input. 

  - {Make Input 2} - Makes the selected outputs into Input 2. The Physical connector display will turn white to indicate it is now an input.
    
**Change input to output**

1. Tap a patched input - an additional Make Output option will light up near the Output Destination Universe box.
    
2. Tap {Make Output} - The Connector will now output DMX.
    
**DMX refresh rate**

Sometimes older equipment cannot handle the higher refresh rates, so it may be reduced with the DMX Max Rate wheel. It is not recommended to go below 28Hz as some flickering may be observed.

**SubNet view**

ArtNet is designed in blocks of 16 universes. 

The blocks starts at subnet 0 and increments by 1 every 16 universes. 

The subnet number and fixture number in the subnet can be viewed by toggling {Subnet View}.

Enable the Subnet view through the dedicated key on the right of the destination universe box to visualize the subnet number instead of the universe number on the ArtNet universes.

**Unicast**

By default the protocol transmission is Broadcast, if a Unicast or Multicast transmission needs to be set, tap on the Unicast Settings toggle key. It is possible to set specific IPs to send the output to. If there is a port configured to a specific IP it will not be sent broadcast. 

The Unicast Settings allow to Add or Delete the IP addresses that will be used for the Unicast or Multicast transmission.

Any IP address may receive the whole protocol with all its universes, or only a part of it as defined in the "From Port" and "To Port" fields.

Ports that are not defined as unicast will be still sent as broadcast. 

Each port can be configured to multiple IPs, more ports can be sent to the same IP.

**Configure Unicast:**

1. Tap on the protocol in DMX Settings popup.

2. Toggle to _Unicast Settings_ to open the unicast popup.

3. Tap Add to add a new IP line or Delete to remove an existing IP

`r create_image_tag("05.Patch", "5.4-Unicast-Settings")`

> On the first line – ports 1 ⟶ 5 will be sent to IP 172.16.10.10

> On the second line – port 5 will be sent also to IP 172.16.10.11

> On the third line – ports 6 ⟶ 10 will be sent to IP 172.16.10.12

### sACN

`r create_image_tag("05.Patch", "5.4-DMX-Settings-sACN")`

**Enable sACN output**

- Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.

1. Under the Protocol heading, tap {sACN} - The selection will turn red.
    
2. Under Broadcast Options tap {Out} - The status indicator light will turn green. The console will now be outputting the selected protocol on the EtherCON Data ports.
    
**Reroute Console Universes:**

1. Under the **Source Universe** header, scroll the list to the source console universe number you wish to route. Once tapped, the selection will turn red. A universe number may also be typed from the keypad.
    
2. Under the **Destination Universe** header, tap one of the cells in the destination universe grid. The source universe number will now be routed through the destination universe number.
    
**Additional functions:**

- Clear a destination universe - Tap {Universe #} in the destination grid. Tap {Clear}.
    
- Clear all destination universes - Select the protocol to clear. Tap {Clear All}.
    
- Reset default route for a single destination universe - Tap {Universe #} Tap {Config}.
    
- Reset all defaults for the selected protocol - Tap {Config All}.

**Enable Input / Output**

Use the Broadcast Option keys to enable / disable the Input and the Output, to either receive or send the protocol.

When the green dot is shown on the key, the protocol is set as enabled. Tap apply to activate it.

<span style="color:blue">**Input** on the ACN protocol is not implemented yet.</span>.

**Remap Input / Output**

Toggle between In (Receive) and Out (Send) on the top of the view to either show the input or the output universes configuration in the destination universe box.

1. Open the {DMX SETTINGS} from Vibe Menu > Settings or tap the DMX Settings button - The DMX Properties popup will open.
    
2. In the Protocol column, Tap {ACN}.
    
3. Under the Source Universe heading, tap the desired source universe number or once red type the universe number you wish to be the source.
    
4. Under the Local Output Destination Universe heading, tap one of the displayed local outputs - the source Universe will now be patched to the output.

👉 Use the Clear All and the Config All keys to remap the protocol on a 1:1 basis.
    
**Change output to input** 

- Currently Vibe supports 2 inputs but multiple connectors may be assigned to the same input.

1. Tap a patched output - Two additional options will light up near the Output Destination Universe box. 

  - {Make Input 1} - Makes the selected outputs into Input 1. The Physical connector display will turn white to indicate it is now an input. 

  - {Make Input 2} - Makes the selected outputs into Input 2. The Physical connector display will turn white to indicate it is now an input.
    
**Change input to output**

1. Tap a patched input - an additional Make Output option will light up near the Output Destination Universe box.
    
2. Tap {Make Output} - The Connector will now output DMX.
    
**Change DMX refresh rate**

Sometimes older equipment cannot handle the higher refresh rates, so it may be reduced with the DMX Max Rate wheel. It is not recommended to go below 28Hz as some flickering may be observed.

**Priority**

ACN universes may have a priority to manage networks where more than one ACN is transmitted.

Turn the Priority wheel, or select it and give a numeric input, to configure the whole protocol's priority.

Tap on a destination universe box and then tap on the Priority key to open the Port Priority popup and set a priority to the specific selected universe.

**Unicast**

By default the protocol transmission is Broadcast, if a Unicast or Multicast transmission needs to be set, tap on the Unicast Settings toggle key. It is possible to set specific IPs to send the output to. If there is a port configured to a specific IP it will not be sent broadcast. 

The Unicast Settings allow to Add or Delete the IP addresses that will be used for the Unicast or Multicast transmission.

Any IP address may receive the whole protocol with all its universes, or only a part of it as defined in the "From Port" and "To Port" fields.

Ports that are not defined as unicast will be still sent as broadcast. 

Each port can be configured to multiple IPs, more ports can be sent to the same IP.

**Configure Unicast:**

1. Tap on the protocol in DMX Settings popup.

2. Toggle to _Unicast Settings_ to open the unicast popup.

3. Tap Add to add a new IP line or Delete to remove an existing IP

`r create_image_tag("05.Patch", "5.4-Unicast-Settings")`

> On the first line – ports 1 ⟶ 5 will be sent to IP 172.16.10.10

> On the second line – port 5 will be sent also to IP 172.16.10.11

> On the third line – ports 6 ⟶ 10 will be sent to IP 172.16.10.12

### DMX Input

**The following objects may be mapped to DMX inputs** 

- DMX input mapped directly to the console's DMX outputs 

- DMX input mapped to Fixtures 

- DMX input mapped to Controllers 

- DMX input mapped to Macros 

**Map a DMX output to a DMX input**

1. Press \[ADDRESS] \[#]
    
2. Tap {INPUT PATCH TO} on the toolbar - Command line will say INPUT PATCH TO
    
3. Press \[ADDRESS] \[#]
    
4. Press \[STORE]
    
> \[ADDRESS] \[1] {INPUT PATCH TO} \[ADDRESS] \[1] \[STORE] - When DMX 1 is received from an external source like a console, DMX 1 will directly output to the Vibe DMX output. No values will be shown in the live display as no actual parameters are involved.

**Map a range of DMX outputs to a range of DMX inputs**

1. Press \[ADDRESS] \[#] ⟶ \[#]
    
2. Tap {INPUT PATCH TO} on the toolbar - Command line will say INPUT PATCH TO.
    
3. Press \[ADDRESS] \[#] ⟶ \[#]
    
4. Press \[STORE]
    
**Map a Fixture to a DMX input**

1. Press \[ADDRESS] \[#]
    
2. Tap {INPUT PATCH TO} on the toolbar - command line will say INPUT PATCH TO
    
3. Press \[Fixture] \[#]
    
4. Press \[STORE]

> DMX inputs will automatically be mapped to all the fixtures parameters starting at the specified address. \[ADDRESS] \[1] \[FIXTURE] \[1] (A fixture with 42 parameters) \[STORE] will automatically match the 42 parameters to input addresses 1 → 42. The next fixture would have to be mapped starting at address 43.

**Map a controller to a DMX input**

1. Press \[ADDRESS] \[#]
    
2. Tap {INPUT PATCH TO} on the toolbar - Command line will say INPUT PATCH TO.
    
3. Press \[PLAY-B] (Controller) - The Controller Selection popup will appear.
    
4. Choose the Controller Type, Page Number, and Controller number from the popup.
    
5. Press ENTER, or tap Apply to close the popup and complete the patch.
    
`r create_image_tag("05.Patch", "5.4-Controller-Selection")`

**Map a Macro to a DMX input** - Macro will trigger at 50%

1. Press \[ADDRESS] \[#].\[#]
    
2. Tap {INPUT PATCH TO} on the toolbar - Command line will say INPUT PATCH TO.
    
3. Press \[MACRO] \[#]
    
4. Press \[STORE]
    
**Delete a DMX Input patch assignment**

1. Press \[ADDRESS] \[#]
    
2. Tap {INPUT PATCH TO} on the toolbar - Command line will say INPUT PATCH TO
    
3. Press \[DELETE]

### DMX In/Out View

DMX Output and Input view is meant to show in real time the output and input values of each DMX channel of the selected universe.

`r create_image_tag("05.Patch", "5.4-DMX-View")`

Use the view's menu to select the target output or input universe.

DMX values can be shown in numeric or in graphic visualization.


## Fixture View {#Fixture-View-5.5}


- The fixture view lists all the created fixtures and their patch information.

`r create_image_tag("05.Patch", "5.5-Fixtures-View")`

- Select a Set on the **Sets View** to filter the fixtures listed.

- Use the Fixture# column to select the fixtures and the \[DESELECT] button to release the selection. Selected fixtures will be highlighted in yellow.

**Renumber Fixtures**

- Tap on the Set or on the Set number column of a fixture selection, or tap the {RENUMBER} key on the patch toolbar, to change the fixture Set and ID.

**Rename Fixtures**

- Tap on the name column of a fixture selection to change the fixture Name.

- Renaming multiple fixtures at once is possible by using the # at the end of the text.

**Re-patch Fixtures**

- Tap on the DMX Address column of a fixture selection, or tap the {PATCH} key on the patch toolbar,  to change the fixture address.

**Change Fixtures' Mode**

- Tap on the Mode column of a fixture selection to change the fixture mode.

- Different personalities of the same device need to be imported in the show.

**Invert Pan/Tilt**

- Tap on the Pan Invert, Tilt Invert, Pan/Tilt Swap columns of a fixture selection to change the fixture position parameters' behavior.


## Address Properties {#Address-Properties-5.6}


The address view lists all the DMX addresses of the selected universe and their properties.

Each cell contains the properties of a DMX address and the icon of the parameter patched on it.

`r create_image_tag("05.Patch", "5.6-Address-View")`

- To edit address properties, tap on the addresses to select them and then "Address Properties" on the header. The Address Properties popup will open.

`r create_image_tag("05.Patch", "5.6-Address-Properties")`

- The following address properties can be edited:

  - **Proportional Level**: limits the highest value that the address can reach.

  - **Base**: limits the lowest value that the address can reach.

  - **Curve**: assigns to the address a specific curve. Default is a Fade In curve.

  - **Grand Master**: defines if the address is under the Grand Master's control. Default is ON for the dimmer parameters and OFF for the other parameters.

  - **Restore Defaults**: restores the default address properties.


## Park {#Park-5.7}


`r create_image_tag("05.Patch", "5.7-Park-Address")`

**Park an address:**

1. \[ADDRESS] \[#] {PARK} - The Park popup will appear.
    
2. Set a DMX level from 0 ⟶ 255 using the virtual slider.
    
3. Tap Apply or press \[ENTER] to close the popup and park the address.

**Unpark an address:**

1. \[ADDRESS] \[#] {PARK} - The Park popup will appear.
    
2. Tap {Clear Park}.
    
3. Tap Apply or press \[ENTER] to close the popup and unpark the address.
    
**Park a fixture:**

1. \[FIXTURE] \[#] {PARK} \[STORE] 

Fixture will now be parked at the current values.
    
**Unpark a fixture:**

1. \[FIXTURE] \[#] {PARK} \[DELETE] 

**Park a parameter:**

1. \[FIXTURE] \[#] {PARAMETER} {PARK} \[STORE] 

The Parameter will now be parked at the editor value.

**View parked fixtures and address:**

In the Exam view tap Patch and then Park to check all the parked addresses and fixtures.
    
><span style="color:Red">> The Grandmaster **does not** affect parked addresses and fixtures. </span>

><span style="color:Red">> The \[B.O.] key **does** blackout parked addresses and fixtures. </span>


## Clone {#Clone-5.8}


Vibe has smart and advanced clone features.

The Fixture Cloning feature allows to copy all the stored data from a selection of fixtures to another one.

To open the fixture cloning popup, press the dedicated button in Patch page's Editor Toolbar.

`r create_image_tag("05.Patch", "5.8-Clone-Fixture")`

Choose the order of source fixtures on the left column and the order of destination fixtures on the right column, then press Done.

Vibe will provide a smart fixture cloning keeping the fixtures' data as similar as possible.

Selection Rules:

- All source fixtures must be of the same type.

- All destination fixtures must be of the same type.

- Many fixtures can be cloned to many fixtures, but the amount must be the same.

- It is possible to select 1 source and many destinations.

The fixture cloning operation is not reversible, so there is no undo once hitting the DONE button.

**Exchange Clone**

The Cloning option on the top can be set as a one sided or a two-sided clone.

A one-sided clone copies the stored data from the source to the destination fixtures only.

A two-sided clone, called Exchange Clone, makes a smart replacement of data from the source fixtures to the destination fixtures and vice versa.

**Advanced Clone**

The Advanced fixture cloning option on the top enables access to a pair of Next popup windows where the matching parameters can be filtered, forced, and customized by the user.

The next step shows the Parameter Selection window.

`r create_image_tag("05.Patch", "5.8-Clone-Param")`

The cloning can be based on raw values, preserving the parameters' levels, or on smart values, preserving the fixture's functions. Raw values means that Vibe will match between parameter types and copy the raw value. Smart means that Vibe will try to find the real data information of the parameter and convert the values to match the destination fixture to look the same. Default is Smart.

On the right side there is a match table between the source and destination fixtures parameters. This table is dynamic and shows the data set from the left side. User can also change matching parameters manually, but this is only to very special cases and anyway it is not recommended. SMART will anyway overrule the table in case there is a parameter that is included in the smart.

The next step shows the Data window.

`r create_image_tag("05.Patch", "5.8-Clone-Data")`

The Data window permits to filter the Groups, Libraries, Qlists, Scenes and Submasters, to apply the cloning only to the selected contents. Default is that all are selected.

NOTE: on the exchange option, these lists will show objects from both source and destination fixtures.

There is an option to clone the calibration data, so the destination fixture will get the same location coordinates as the source fixture. Default is Disabled, because in real world 2 fixtures cannot have the same physical position, but can be enabled, for example in case of fixture switches or if working on a 3D visualizer trying different lighting setups on the same rig.

There is an option to clone the look ahead mask so if the source fixture is in the mask, then the destination fixtures will also be in the mask. Default is Enabled.

There is an option to choose what to do with the parameters of the destination fixtures that are not included in the clone because they were not matched or any other reason. Merge means to keep these values, overwrite will delete the values. Default is Overwrite.


## Replace {#Replace-5.9}


Vibe has smart and advanced device replacement.

The Device replacement feature allows to replace a device with another one, keeping all the matching data stored.

To open the device replacement popup, press the dedicated button in Patch page's Editor Toolbar.

`r create_image_tag("05.Patch", "5.9-Replace-Fixture")`

Choose the Source device on the left column and the new device from the Imported Devices on the right column, then press Done.

Vibe will provide a smart device replacement keeping the fixtures' data as similar as possible.

The device replacement operation is not reversible, so there is no undo once hitting the DONE button.

**Advanced Replacement**

The Advanced replacement option on the top enables access to a Next popup window where the matching parameters can be filtered, forced and customized by the user.

The next step shows the Parameter Selection window.

`r create_image_tag("05.Patch", "5.9-Replace-Param")`

Each bank has its option to enable/disable. Enabled means it will be included in the Device replacement and disabled means it will not be included. Default is enabled.

The replacement can be based on raw values, preserving the parameters' levels, or on smart values, preserving the fixture's functions. Raw values means that Vibe will match between parameter types and copy the raw value. Smart means that Vibe will try to find the real data information of the parameter and convert the values to match the destination fixture to look the same. Default is Smart.

On the right side there is a match table between the source and destination fixtures parameters. This table is dynamic and shows the data set from the left side. User can also change matching parameters manually, but this is only to very special cases and anyway it is not recommended. SMART will anyway overrule the table in case there is a parameter that is included in the smart.


## Calibration {#Calibration-5.10}


Calibration Data give to the Vibe all the information regarding the fixture positioning on the stage, defined by X, Y, Z coordinates and Rotations around the axes, based on the point identified as stage center.

{Fixture Calibration} key on the Patch Toolbar opens a popup used to calibrate the fixtures through the XYZ coordinates, that may be either taken from a 3D Visualizer or from a real measurement. 

`r create_image_tag("05.Patch", "5.10-Fixture-Calibration")`

When fixtures are properly calibrated it is possible to specify a stage point on Vibe xyz position picker to automatically point all the fixtures on it. 

Another advantage of the fixture calibration is to speed up the creation of topographical views (Topo).

There are a few passages to get the calibration data of the fixtures from third party software, that depend on which visualizer is used. 

### Import CSV

Most of the 3D visualizers on the market feature a process to export a table of the fixture coordinates into a .csv file.

After exporting the CSV containing the fixtures' positioning coordinates from the visualizer, the .csv file table should be prepared in order to match the column’s order to Vibe and import the Calibration Data. 

**Instructions for Loading an External Fixture Calibration** 

Before beginning, the user must prepare the calibration data in CSV format. 

The file should include the following columns in the specified order:

- A  - # – The fixture ID number in the Visualizer, or the Fixture Name, or leave empty (this field is ignored by the CSV Import process. It may contain anything that helps the user to match the source fixture list to the Vibe fixtures)

- B  - ID – The fixture number in Vibe

- C  - X – The X coordinate of the fixture’s position in meters

- D  - Y – The Y coordinate of the fixture’s position in meters

- E  - Z – The Z coordinate of the fixture’s position in meters

- F  - RotX – The X value of the fixture’s rotation, in degrees

- G  - RotY – The Y value of the fixture’s rotation, in degrees

- H  - RotZ – The Z value of the fixture’s rotation, in degrees

`r create_image_tag("05.Patch", "5.10-CSV-Sample")`

Notes: 

- The 1st line with column headers is not important, but the order of the columns must be exactly as listed above.

- Empty fields are considered as 0 (zero) values.

- Eventual additional columns must be deleted.

Once the CSV file is ready, move it to the following directory in the Vibe installation:

vibe/compulite/userdata/

To import the calibration data in Vibe:

Open a Patch page.

Click the "Fixture Calibration" button on the taskbar.

Click the "Import Calibration Data" button.

Use the file explorer to select your CSV file and click OK.

`r create_image_tag("05.Patch", "5.10-Import-CSV")`

A popup will appear displaying the data read from the CSV file.

Rows where Vibe could not match the fixture number to an existing fixture will not be shown.

The data may be edited within the popup before applying it. 

Click OK to apply the calibration.

### Wysiwyg

As an alternative to the CSV import, calibration data may be manually copied from Wysiwyg.

1.  On Vibe, go to \[PATCH] page and tap on {FIXTURE CALIBRATION}.
    
2.  Tap on {Stage} button and set the stage dimensions.
    
3.  On Wysiwyg, specify the drawing origin point at the center of the stage. For this, it will be necessary to work in the CAD tab using the TOP view. Press on the top left corner (that connects the vertical ruler and the horizontal ruler – (see <span style="color:LightSkyBlue">Blue Frame</span>) and select the option of 'Mover Ruler (Set View Origin)ʼ.
    
4.  Select the center of your stage (see <span style="color:Red">Red Arrow</span> in the Picture)
    
`r create_image_tag("05.Patch", "5.10-Wysiwyg-Calibration")`

5. Go to 'Data tab', press Option on the toolbar ⟶  Document Options ⟶  Draw Defaults - and  change the units to metric.

`r create_image_tag("05.Patch", "5.10-Wysiwyg-Calibration-Data")`

6. Copy these values to the Fixture calibration table in Vibe:

  - the column X to the column X, 

  - the column Y to the column Y, 

  - the column Z to the column Z.

7. After all values are in the Vibe fixture calibration table, select the X column (by tapping the header) and press \[-]. 

8. Fixtures are now calibrated.

### Capture

As an alternative to the CSV import, calibration data may be manually copied from Capture.

1. On Vibe, go to \[PATCH] page and tap on {FIXTURE CALIBRATION}.
    
2. Tap on {Stage} button and set the stage dimensions.
    
3. On Capture, place the center of the stage in the intersect point of the 2 Bold Axis, when the CAD displays a view from the Top

`r create_image_tag("05.Patch", "5.10-Capture-Calibration")`

4. Go to Tools ⟶  Options and change the measurements to metric.

5. Select a fixture in Capture to see the XYZ coordinates when the table is showing 'Selected Itemsʼ. 

`r create_image_tag("05.Patch", "5.10-Capture-Calibration-Data")`

6. Copy these values to the Fixture calibration table in Vibe:

  - the column X to the column X, 

  - the column Y to the column Z, 

  - the column Z to the column Y.

7. After all values are in the Vibe fixture calibration table, select the X column (by tapping the header) and press \[-], and select the Y column and press \[-]. 

8. Fixtures are now calibrated.

### L8

As an alternative to the CSV import, calibration data may be manually copied from L8.

1. On Vibe, go to \[PATCH] page and tap on {FIXTURE CALIBRATION}.
    
2. Tap on {Stage} button and set the stage dimensions.
    
3. On L8, go to ROOM environment and set the 'World Center' to define the center of the stage. Eventually an object with zero-sized dimensions can be created and set as world center. Ensure that the measurement is set on metric.

`r create_image_tag("05.Patch", "5.10-L8-Calibration")`

4. Go to DMX environment. All the fixtures' coordinates are now based on the world center. 

5. Select a fixture in L8 from the list on the left side of the screen to see the XYZ coordinates.

`r create_image_tag("05.Patch", "5.10-L8-Calibration-Data")`

6. Copy these values to the Fixture calibration table in Vibe:

  - the column X to the column X, 

  - the column Y to the column Z, 

  - the column Z to the column Y.

7. Fixtures are now calibrated.

### VectorWorks

As an alternative to the CSV import, calibration data may be manually copied from VectorWorks.

<span style="color:Gray">Coming Soon.</span>

### Depence

As an alternative to the CSV import, calibration data may be manually copied from Depence.

<span style="color:Gray">Coming Soon.</span>


## Auto-Patch {#Auto-Patch-5.11}


Vibe can automatically get the device list, fixture patch and calibration data, by loading and converting an MVR show file.

As an alternative to the MVR show import, Vibe integration with some visualizers allows to automatically get the fixtures' information by establishing a specific network connection with the third party software, that depends on which visualizer is used.

### Wysiwyg

**Auto Patch from Wysiwyg** may be done by installing the Compulite - Wysiwyg driver.

First download the **Compulite driver for Wysiwyg** from: http://www.compulite.com and then install the driver:

1.	Run the file CompuliteWYSIWYG_DriverSetup.exe.

2.	Read the licence terms and click I Accept to continue.

3.	Choose the Compulite consoles for which the driver will install.

4.	After reading the information displayed, tap INSTALL.

5.	Tap FINISH.

The computer running the Wysiwyg software must be configured to the same subnet as the Compulite console.

Use the Data port to connect to the PC running Wysiwyg (On Vibe PC use any Ethernet port).

Enable VC transmission on Vibe.

After completing the patch procedures in Wysiwyg, **establish the connection** between the console and the Wysiwyg application.

`r create_image_tag("05.Patch", "5.11-Wysiwyg-connect-viz")`

1.	In the Wysiwyg application, click the Live tab.

2.	Open the Live menu.

3.	Choose Device Manger.

4.	Click New.

5.	Search for your Console by using the search bar or by expanding the Consoles -> Manufacturer nodes and choosing Compulite.

6. Click Insert.

7.	Click on the console and choose Properties. In the protocol field make sure "Compulite VC" is selected.

8.	In the Address field, enter the console’s IP address.

9.	Bind Wysiwyg Universes to Vibe output ports. Under Universe, click to open drop selection and select a Wysiwyg universe. Do so for every port you wish to bind. Alternatively select multiple rows and click "Assign", then select a Wysiwyg universe to bind all selected ports.

10.	Close the properties window.

11.	Click Connect.

12.	Verify that the status now shows Connected.

13.	Click Close.

A popup will show that a Wysiwyg client is now connected.

`r create_image_tag("05.Patch", "5.11-Wysiwyg-connect-vibe")`

Use **Wysiwyg Auto Patch feature**:

`r create_image_tag("05.Patch", "5.11-Wysiwyg-autopatch")`

1.	In the Wysiwyg application, click the Live Wysiwyg tab.

2.	Open the Live menu.

3.	Choose Auto Patch.

4.	Click Send Patch.

5.	Click Close, to close the dialog box.

`r create_image_tag("05.Patch", "5.11-Wysiwyg-patch-sent")`

A popup on the Vibe screen will ask to accept the autopatch from Wysiwyg. Tap Apply.

`r create_image_tag("05.Patch", "5.11-AutoPatch-Wysiwyg")`

A popup on the Vibe screen will ask to save the current show file.

`r create_image_tag("05.Patch", "5.11-AutoPatch-Wysiwyg-apply")`

A popup on the Vibe screen will show the matched devices and allows to match them in a different way or to built the unmatched ones as new devices.

`r create_image_tag("05.Patch", "5.11-AutoPatch-Wysiwyg-Device")`

When all the devices are matched, tap Apply and the convert process will start.

### Capture

**Auto Patch from Capture** may be done via the CITP protocol.

It is possible to sync the show from Capture. In order to do that, set the Capture CITP settings to use Standard Multicast and select the relevant IP address.

`r create_image_tag("05.Patch", "5.11-AutoPatch-Capture")`

In addition, make sure Vibe and Capture are on the same subnet. 

After finishing preparing the show on Capture, go to Vibe, open the CITP popup, enable CITP and connect to Capture from the Visualizers tab. 

Then _Get Data_ from Capture and Vibe will be ready to go.




