
# MultiUser

👉 **Connect** to a Vibe session to program and control the show with more consoles and operators working together in real time.

This chapter deals with connecting more consoles to the same network and configuring the users.

**Chapter index:**

-  [18.1 Master/Backup](#Master/Backup-18.1)
-  [18.2 Users](#Multi-User-18.2)


## Master/Backup


Master/Backup is the basic way to connect two Vibe systems and make them work simultaneously on the same show file.

In order to establish a Master/Backup connection, the two Vibe consoles must be in the same network and must run the same Vibe software version.

👉 <span style="color:gray"> Any Vibe console can work in a MultiUser Session, while the VibePC needs to install a **Network Licence** to enable the networking. Not implemented yet.</span>.

**Connection Process**

On the Vibe console that has to become the Master, open the Network Settings to start the **Session**.

`r create_image_tag("18.MultiUser", "18.1-Main-Network")`

- Verify the Network Adapter and IP address used, refresh them if changes are applied.

- Tap on the **Start Session** key. The Console State changes from **Stand Alone** to **Master**.

`r create_image_tag("18.MultiUser", "18.1-Start-Session")`

- On the Backup console select the Master console from the **Online IP Devices** box.

- Tap on the **Connect as Backup** key.

`r create_image_tag("18.MultiUser", "18.1-Backup")`

- The Backup console gets a **Connect Request** popup. 

`r create_image_tag("18.MultiUser", "18.1-Connect-Request")`

- Tap Approve and wait for the Show Sync Progress bar to finish on both consoles.

`r create_image_tag("18.MultiUser", "18.1-Sync-Master")`

`r create_image_tag("18.MultiUser", "18.1-Sync-Backup")`

- The Backup console gets a **Layout Sync Request** popup.

`r create_image_tag("18.MultiUser", "18.1-Sync-Backup-Layout")`

- Tap Apply to synch the layout too, or Cancel to keep the layouts separate.

- A popup on both systems informs when the connection is ready.

`r create_image_tag("18.MultiUser", "18.1-Master-Ready")`

- In the Status Box, a green line shows that the connection is established, and the consoles' command lines show if the console is the Master or the Backup.

`r create_image_tag("18.MultiUser", "18.1-Master-Command")`

`r create_image_tag("18.MultiUser", "18.1-Backup-Command")`

When the Master/Backup connection is ready, both the Vibe systems run the same show and use the same outputs, the ones of the Master.

Any operation that is done either on the Master or on the Backup is synchronized in real time on the other system.

👉 Master and Backup consoles share also the Editor, so the programming operations should be done on one system at a time otherwise they will be merged.

**Disconnection Process**

To manually end the whole network session, on the Master's network settings tap on **End Session** key.

To manually end the synchronized connection:

- Open the Network settings on either the Master or the Backup console.

- Tap on the **Disconnect** key.

`r create_image_tag("18.MultiUser", "18.1-Disconnect")`

- Wait for the Disconnect Progress bar to finish.

`r create_image_tag("18.MultiUser", "18.1-Disconnect-Progress")`

- The **Partner Disconnected** advice appears on both consoles.

`r create_image_tag("18.MultiUser", "18.1-Partner-Disconnected")`

The **Partner Disconnected** advice appears also in case of connection failure (for example if the cable is disconnected or if one console fails or loses power).

If the connection with the Master fails, the Backup will automatically take control of the outputs, ensuring that the show won't lose any data.

The Command Line informs that the connection with the partner is lost.

`r create_image_tag("18.MultiUser", "18.1-Partner-Disconnected-Command")`

If a lost connection is restored, a popup appear on both systems to inform the user that the other system is online again and ask which option to choose.

`r create_image_tag("18.MultiUser", "18.1-Reconnect")`

- Stand Alone - the consoles will use the show independently from each other, leaving the session.

- Offline - the console will keep the show but disables the outputs, without leaving the session.

- Master - the console will be the Master, performing a full sync operation to make the other console the Backup.

- Backup - the console will be the Backup, performing a full sync operation to make the other console the Master.

<span style="color:gray"> In a MultiUser Session there may be different type of Clients connected. The Client type affects the system's rights of use and limits the operations that can be done from it. The Client type may be **Backup** (Primary Client), **Normal** (Secondary Client), **Low** (Basic Client). Not implemented yet.</span>.


## Users


<span style="color:blue">Not implemented yet.</span>.

<span style="color:gray"> Users popup allows to configure and assign user rights to the Vibe systems on the same network that are connected to the Master console's session.</span>.

`r create_image_tag("18.MultiUser", "18.2-Users")`

<span style="color:gray"> Each User Client has specific authorizations and limitations for managing the Master console's show patch, program and playback properties.</span>.

<span style="color:gray"> The User right may be assigned with Default options or Customized.</span>.

