---
output:
  pdf_document: default
  html_document: default
---
# Introduction

This chapter discusses getting started with your Compulite Vibe console.

**The following is covered in this chapter:**

-   1.1. Unboxing
-   1.2. Getting Started
-   1.3. Guide Conventions
-   1.4. Important Terms
-   1.5  Releases

## Unboxing

TBA.

## Getting Started

**Power requirements:**

- Vibe uses a power supply that supports 90-264V at 47-63 Hz.
- Approximately 3.2 amps at 230V.
- Input uses a Neutrik powerCON connector ended with the appropriate male connector for the destination country.

**Desk Light:**

- Insert the goose neck desk light into the 3 pin XLR on the rear of the console.
- <span style="color:DarkGray">Desk light intensity is controlled in the {System Settings} {Hardware} tab.</span> 

Monitor intensity:
- <span style="color:DarkGray">Monitor intensity is controlled in the {System Settings} {Hardware} tab.</span> 

**Power up the console:**

- Insert the supplied powerCON male connector into the female connector located on the rear of the console. Align the guide slots and turn clockwise untill the connector locks.
- Turn on the power supply switch above the powerCON connector.
- Press the Power button located at the upper right corner of the monitor panel above the USB connectors.
- The operating system will boot and the Vibe console software will automatically launch.

**Power down the console:**

- Tap the {Vibe} menu key beside the command line on the main display - The Vibe Menu will open.
- Tap {Exit} - The {Exit Vibe} Pop-up will appear.
- Tap {Yes} or {No}.
- The Vibe application will shutdown and a screen will appear with the following options:
    - <span style="color:DarkGray">{Shut Down the Console} - System will power off.</span>
    - <span style="color:DarkGray">{Restart Vibe} - Vibe console application will restart.</span>
    - <span style="color:DarkGray">{Open Offline Tool} - the Vibe utilities app will open. Hardware and software updates are preformed in the Offline Tools app.</span>

- Choose Shut Down the Console - The console will safely power off.

## Guide Conventions


- **[XXXX]** - Physical key

- **{XXXX}** - Soft key

- **[ ]** **{ }** - Example

- **Press** - Action applied to a physical key

- **Tap** - Action applied to softkey or virtual key

- **Toggle** - Action that actives and deactivates with alternating taps or presses

- **Key** - Any physical or virtual key that is NOT used for controller activation

- **Button** - Any virtual or physical key that is used to activate a controller

- **Keypad** - Embedded numeric keypad

- **Keyboard** - Console's pull-out ASCII keyboard or any external keyboard

- **SK -** Object softkeys (Libraries, Groups, Snap, Macros, etc.)

- 👉 **-** Hint or suggestion

- <span style="color:Red">**RED**</span> **-** Important information or Caution

- **[Here]** - Short form for Press an appropriate destination softkey or controller button to complete the command

## Important Terms


-   **DMX 512 Output/Input Port** - One of the 8 physical 5 pin XLR connectors on the back of the console. Although the gender is female, any connector may be configured as an input but must use a turnaround adapter.
    
-   **DMX 512 Universe** - Virtual DMX outputs 0 ⟶ 256 that may be routed to the 8 physical outputs and/or any of the three supported DMX over Ethernet protocols. 

    ◾ Compulite VC protocol 

    ◾ w Art-Net 3 w 

    ◾ sACN
    
-   **SET** = Fixture numbering syste 
    - 0 = Fixtures, (Default, includes all sets) 
    - 1 = Channels (Conventional fixtures)
    - 2 = Spots (Automated heads and mirrors) 
    - 3 = Matrix (LED pixel-based fixtures) 
    - 4 = Servers (Video servers) 
    - 5 ⟶ 1000 = User defined sets
    
-   **Parameter** - An individual feature of a fixture such as dimmer, pan, tilt, color wheel, gobo.
    
-   **Controllers** - Any physical or virtual control that executes or plays back system objects such as cues, scenes, macros, and snapshots.
    
-   **Submaster** - A special type of Scene where stored fixtures inhibit their dimmer values proportionate to their assigned slider controller value.
    
-   **Master Controller** - Playback section of the console with large [GO], [BACK], [HOLD] keys.
    
-   **Slider** - Slide potentiometer often referred to as a **Fader**.
    
-   **Qkey** - A single button Controller.
    
-   **Assert** - Takes back control of parameters that have been "robbed" by other controllers.
    
-   **HTP (Highest-Takes-Precedence)** - When values from two or more controllers are summed, The highest value will output to the stage. Used mainly for dimmer values in theater applications.
    
-   **LTP (Latest-Takes-Precedence)** - When similar parameters are on two or more controllers, the last asserted parameter will output it's values to the stage no matter what the value.
    
-   **[SELECT]** - Multi-use key, mainly used to assign any controller as the Master Controller. Commands not specifying a Qlist destination will be applied directly to the [SELECT] Master Controller.
    
-   **Qlist** - A Folder containing cues. Each Qlist has its own unique numbering system from 0.001 to 999.999.
    
-   **Cue** - A look (record) contained within a Qlist. Cues contain stored parameter values **and** properties such as text label and time values.
    
-   **Scene** - A look that exists independent of a Qlist.
    
-   **Library** - Container of frequently used fixture parameter values (Bank Library) or system objects (Object Library) . Bank Libraries may be created as referenced or unreferenced. The default for most libraries is referenced.
    
-   **Options** - Used to modify object properties "on the fly"
    
-   **Settings** - Used to modify object properties and behaviors **after** an object has been created.
    
-   **Cue Zero** - The starting point at the top of a Qlist. Release may or may not return to the top of a Qlist depending on Qlist Properties. Cue Zero will always return to the top of the Qlist. The command Cue 0 GOTO is valid.
    

>👉 For the sake of this guide, **Channel, Spot, Matrix, and Server Sets** will be referred to as **Fixture** because the Fixture Set can reference all the other sets

>👉 Some keys have two functions when used with the [VIBE] key (shift key). In this case, the key label on the bottom is the default, and top label is the shifted function.

## Releases

### R.3.0

- Release Date: **06/09/2020** 
- DB version: **R_3.0** 
- Desktop version: **R_3.0** 
- LPU version: **R_3.0** 
- HAL version: **R_3.0** 
- Device Pack version: **DP_3.0**


#### Bug Fixes
-   Fixed a crash when removing a point from the Function editor
    

-   Fixed a crash when searching Exam View and pressing SHIFT+RESET
    

-   Fixed a potential crash on startup
    

-   Fixed a potential crash on Undo popup
    

-   Fixed potential crash on HAL
    

-   Fixed a crash when pressing Actions on the Timeline view
    

-   Fixed a crash when pressing apply on the Link Cue popup
    

-   Fixed a crash on LPU when deleting a cue that is next on a PB and it's values are active as Look Ahead
    

-   Fixed a crash on LPU when releasing a playback during loop could cause it on some cases
    

-   Fixed a crash on filters popup when deleting the last parameter from the list
    

-   Fixed a crash when deleting a device that had no fixtures in the show
    

-   Loading a big show could cause the system to get stuck
    

-   Rem Dim could cause errors on DB
    

-   Grab Active Master PB could cause errors on DB
    

-   Live View - When parameter jumping is on its should works all the cases
    

-   Performance fixes in specific sequences as well as general system speed
    

-   Fixture selection was slow and caused many updates to small screen, especially when selecting with '+'
    

-   When fixture has values, entering to Blind editor where the values there are at home, will make a graphic flick
    

-   "Exclude from Snap" and "Exclude from Override" did not work correctly **Snaps stored with these options need to be rebuilt!**
    

-   It was not possible to select/deselect a cell on the first column in Cell Time popup
    

-   Exam of a new device did not show the info on Exam View
    

-   Exam view did not refresh after deleting a Qlist
    

-   Wheel picker sometimes was not accurate and selected the wrong step
    

-   Address test delta value was showing wrong value
    

-   Changes to Address properties did not output unless applying the popup
    

-   Fixtures with more than 1 color layer could make the HIS picker stuck
    

-   Data on the status view was not always refreshed
    

-   Filters popup – changes were not saved if user switched between filters
    

-   Activate a snap after deleting Qlists loaded them in a ghost mode
    

-   Deleting Libraries, Macros, Scenes did not remove them from the snaps they were stored in
    

-   Deleting Snaps did not clear the data correctly
    

-   Master PB did not change according to the data stored in the Snap
    

-   Fixture selection numbers did not cut to the actual maximum number on echoline
    

-   When Lib stored, echoline looks strange
    

-   Sometimes [Transpose] doesn't ordering the fixtures correctly
    

-   Park on parked parameters did not work correctly with Grand Master
    

-   A/B Slider behavior was wrong for manual fade.
    

-   Faders kept sending data even though the value did not change
    

-   Cue time units on popup did not change
    

-   SHIFT+GRAB took a lot of time
    

-   Delete a cue took a lot of time
    

-   Updating cues caused an error on DB and sometimes caused wrong values to be stored
    

-   Release value from Cue did not work correctly
    

-   Updating a copied cue/scene did not update it
    

-   Update cue values from the Tracksheet view did not always work
    

-   Load track data to cue did not load from a block cue
    

-   When updating a cue that after it there is a cue with virtual params stored, the params are changed
    

-   When Lib is stored as block, update the previous cue will make track to the block
    

-   After releasing a parameter from a cue, values look like they 'Block' even though they are tracked
    

-   After remove a reference from a Lib, all cues that are using any Libs will lose their reference
    

-   When updating a Hard value using a referenced Lib it should select the source cue in the update popup
    

-   Updating a Virtual Color Cue to Physical Color via update pop-up will track to the next cue if stored with Virtual Color
    

-   Cannot release a param so it will be tracked again from a Lib
    

-   Release Virtual color to physical color, vice versa, will release to Home
    

-   Release a Virtual Lib to Virtual hard value or Physical Lib to Physical hard value, keeps the notation of the Lib in the Live view
    

-   When storing a Lib, the Library notation and reference in Live is being applied only on the selected fixtures
    

-   Virtual and Physical params are acting weird when "maintain last value" is active
    

-   Can't delete Highlight or Lowlight cues
    

-   Link Cue popup showed error when opened from the toolbar
    

-   If a cue had time-in, time-out and follow in CUT, it was skipping the cue
    

-   Color values are jumping when Qlist is tracking off and follow time is CUT
    

-   Release at bottom took the Qlist release time instead of working in CUT
    

-   Clear editor on master Go, clears the editor in any go
    

-   Color icon is not changing when in Blind mode
    

-   If param is selected, and then you change to 'Parameter Steps' view, it does not show the steps of the param
    

-   Small screen effects showed wrong parameters
    

-   When Randomize fixtures in the effect, and more than 1 pattern is selected, it should shuffle them in the same way
    

-   Randomize an existing effect that has 2 params on the same row via small effect engine after selecting the params is wrong
    

-   Randomize fixtures should randomize only the order of the fixtures
    

-   When Pan effect was running, pressing the Tilt made a jump to 0
    

-   Rate window is flickering with the cues fades
    

-   Context view got back to idle after selecting a library
    

-   Context did not display Filter SK
    

-   The name of context view when its tabbed is wrong
    

-   SMPTE FPS value was wrong
    

-   Group Select/Deselect/Release did not work on Qlists and Scenes
    

-   'Group Release' button stuck the params it releases
    

-   [Shift]+Master [Go][Back] should make a Go\Back on master in Cut time
    

-   RDM settings are not stored in show file
    

-   Edit control - caret remains visible after focusing out
    

-   Fixture Builder: 

    - Errors on edit factory devices with overlapping steps 

    - Editing a show device could cause it to be cloned infinite times 

    - Parameter Step tab did not update the navigation buttons 
    - Edit boxes in Parameter Steps table did not work

    - Memory leaks fixes
    

-   Vector show conversion bugs

#### Version Highlights

Version R_3.0 brings new and updated features as listed below:


**Settings**

- **Controller Default Actions**- It is now possible to set a default controller action for each object type on each controller type.
- **Exit Button Location** - The location for the button to exit the system or close a window was moved

- **Clear Device IP History**- Added this option to clear the cache under the system settings.

- **Show/Hide View Headers**- Added an option to show or hide view headers in order to make room on screen.

- **Softkeys Size Improvements**- It is now possible to make the softkey view very compact

- **Unicast Option for Art-Net And VC**- It is now possible to set specific IPs to send the output to

- **Defaults Changes**- There are some new defaults for: Update popup – new values to master pb Bottom Button on submasters – flash Pan & Tilt Effect default size

**Patch**

- **Edit Sets**- There is an option to edit user-sets on the Sets view

**Workflow**

- **Media Bank**- There is a new bank called Media on the Small Screen

- **Toggle Between Banks**- The combination of SHIFT+# on the keypad will switch a bank on the small screen

- **Cell Time Fan**- It is now possible to fan cell times via the keypad

- **Parameter Profile**- It is now possible to set a profile for parameters to change their fade behavior

**Timeline**

- **Grid View Filters**- It is now possible to filter timelines on the grid view

- **Time Format**- It is now possible to decide the time format on the Timeline View

- **Moving Events**- It is now possible to move events on the Timeline with the wheels

- **Events Selection**- It is not possible to select events by creating a rectangle of selection

- **State Machine Support**- It is now possible to trigger Timeline commands from the keypad + toolbar commands

**Popups**

- **New “Loading” Popup**- There is a new popup for continuous loading

- **Remove Function**- On the effects popup, it is now possible to remove an added function

- **CITP Popup**- There is a new popup for CITP configuration and commands

**General**

- **Auto Patch from Capture**- Using CITP protocol, it is now possible to retrieve patch information from Capture

**Fixture Builder**

- **Option to edit Shutter Picker commands**- It now possible to create/edit commands for the Shutter picker

- **Option to edit Frost Picker commands**- It now possible to create/edit commands for the Frost picker

- **Option to edit Iris Picker commands**- It now possible to create/edit commands for the Iris picker

- **Option to edit Zoom Picker commands**- It now possible to create/edit commands for the Zoom picker

- **Option to edit Blade Picker commands**- It now possible to create/edit commands for the Blade picker

- **Option to edit Focus Picker commands**- It now possible to create/edit commands for the Focus picker

- **New Parameter Types**- Added new parameter types to Vibe

**Offline Tool**

- **Panel Test**- New Panel test mode to check the hardware

- **Midi / SMPTE Test**- New Midi / SMPTE test mode

- **Update Firmware Options**- There are new possibilities to update the console firmware
